version: "3.3"
services:
  app:
    container_name: poketeam
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./docker-data/db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data: