version: "3.7"
services:
  app:
    container_name: poketeam
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo/poketeam-db
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./docker-data/db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data: